routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('page-error', function () {
    return view('admins.layouts.error');
})->name('page-error');

Route::namespace('api')->group(function () {
    Route::namespace('Auth')->group(function () {
        Route::group(['middleware' => 'check-login'], function () {
            Route::get('/login', 'AuthController@login')->name('page-login');
            Route::post('/sign-in', 'AuthController@signIn');
            Route::get('/forgot-password', 'AuthController@forgotPassword')->name('page-forgotPwd');
            Route::post('/get-verify-code', 'AuthController@getVerifyCode')->name('getVerifyCode');
            Route::get('/reset-password', 'AuthController@resetPassword')->name('page-resetPwd');
            Route::post('/change-password-new', 'AuthController@changePasswordNew')->name('changepwdNew');
        });
    });
});

Route::prefix('admin')->middleware(['check-logout', 'auto-logout'])->group(function () {
    Route::get('/', 'AdminController@index')->name('page-admin');
    Route::namespace('api')->group(function () {
        Route::namespace('Auth')->group(function () {
            Route::post('/logout', 'AuthController@logout')->name('logout');
            Route::get('/profile/{user}/edit', 'AuthController@profile')->name('profile.edit');
            Route::patch('/profile/{user}', 'AuthController@updateProfile')->name('profile.update');
            Route::patch('/change-password/{user}', 'AuthController@changePassword')->name('user.changePassword');
        });

        Route::namespace('Roles')->group(function () {
            Route::prefix('roles')->group(function () {
                Route::get('search/{query}', 'RoleController@search')->name('role.search')
                    ->middleware('check-permission-user:manager-user');
                Route::get('{role}/permissions/', 'RoleController@showPermissionsByRole')
                    ->middleware('check-permission-user:manager-user');
                Route::post('{role}/setting/permissions/{permission}', 'RoleController@setPermissionsForRole')
                    ->middleware('check-permission-user:manager-user');
            });
            Route::resource('roles', 'RoleController')->middleware('check-permission-user:manager-role');
        });

        Route::namespace('Users')->group(function () {
            Route::get('users/search/{query}', 'UserController@search')->name('searchUser');
            Route::resource('users', 'UserController')->middleware('check-permission-user:manager-user');
        });

        Route::namespace('Categories')->group(function () {
            Route::get('categories/search/{query}', 'CategoryController@search')->name('searchCategory');
            Route::get('categories', 'CategoryController@index')->name('categories.index')
                ->middleware('check-permission-user:view-category');
            Route::get('categories/create', 'CategoryController@create')->name('categories.create')
                ->middleware('check-permission-user:create-category');
            Route::post('categories', 'CategoryController@store')->name('categories.store')
                ->middleware('check-permission-user:create-category');
            Route::get('categories/{category}/edit', 'CategoryController@edit')->name('categories.edit')
                ->middleware('check-permission-user:update-category');
            Route::patch('categories/{category}', 'CategoryController@update')->name('categories.update')
                ->middleware('check-permission-user:update-category');
            Route::delete('categories/{category}', 'CategoryController@destroy')->name('categories.destroy')
                ->middleware('check-permission-user:delete-category');
        });

        Route::namespace('Brands')->group(function () {
            Route::get('brands/search/{query}', 'BrandController@search')->name('searchBrand');
            Route::get('brands', 'BrandController@index')->name('brands.index')
                ->middleware('check-permission-user:view-brand');
            Route::get('brands/create', 'BrandController@create')->name('brands.create')
                ->middleware('check-permission-user:create-brand');
            Route::post('brands', 'BrandController@store')->name('brands.store')
                ->middleware('check-permission-user:create-brand');
            Route::get('brands/{brand}/edit', 'BrandController@edit')->name('brands.edit')
                ->middleware('check-permission-user:update-brand');
            Route::patch('brands/{brand}', 'BrandController@update')->name('brands.update')
                ->middleware('check-permission-user:update-brand');
            Route::delete('brands/{brand}', 'BrandController@destroy')->name('brands.destroy')
                ->middleware('check-permission-user:delete-brand');
        });

        Route::namespace('Products')->group(function () {
            Route::post('products/upload-editor', 'ProductController@uploadEditor')->name('products.uploadEditor');
            Route::get('products', 'ProductController@index')->name('products.index')
                ->middleware('check-permission-user:view-product');
            Route::get('products/create', 'ProductController@create')->name('products.create')
                ->middleware('check-permission-user:create-product');
            Route::post('products', 'ProductController@store')->name('products.store')
                ->middleware('check-permission-user:create-product');
            Route::get('products/{product}/edit', 'ProductController@edit')->name('products.edit')
                ->middleware('check-permission-user:update-product');
            Route::patch('products/{product}', 'ProductController@update')->name('products.update')
                ->middleware('check-permission-user:update-product');
            Route::delete('products/{product}', 'ProductController@destroy')->name('products.destroy')
                ->middleware('check-permission-user:delete-product');
        });
    });
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

resources/views/admins/layouts/breadcrumb.blade.php
<div class="breadcrumbs">
    <div class="col-sm-4">
        <div class="page-header float-left">
            <div class="page-title">
                <h1>Dashboard</h1>
            </div>
        </div>
    </div>
    <div class="col-sm-8">
        <div class="page-header float-right">
            <div class="page-title">
                <ol class="breadcrumb text-right">
                    <li class="active">Dashboard</li>
                </ol>
            </div>
        </div>
    </div>
</div>

resources/views/admins/layouts/error.blade.php
<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->
<style>
    html{
    }
    body{
        margin: 0;
        padding: 0;
        background: #e7ecf0;
        font-family: Arial, Helvetica, sans-serif;
    }
    *{
        margin: 0;
        padding: 0;
    }
    p{
        font-size: 12px;
        color: #373737;
        font-family: Arial, Helvetica, sans-serif;
        line-height: 18px;
    }
    p a{
        color: #218bdc;
        font-size: 12px;
        text-decoration: none;
    }
    a{
        outline: none;
    }
    .f-left{
        float:left;
    }
    .f-right{
        float:right;
    }
    .clear{
        clear: both;
        overflow: hidden;
    }
    #block_error{
        width: 845px;
        height: 384px;
        border: 1px solid #cccccc;
        margin: 72px auto 0;
        -moz-border-radius: 4px;
        -webkit-border-radius: 4px;
        border-radius: 4px;
        background: #fff url(http://www.ebpaidrev.com/systemerror/block.gif) no-repeat 0 51px;
    }
    #block_error div{
        padding: 100px 40px 0 186px;
    }
    #block_error div h2{
        color: #218bdc;
        font-size: 24px;
        display: block;
        padding: 0 0 14px 0;
        border-bottom: 1px solid #cccccc;
        margin-bottom: 12px;
        font-weight: normal;
    }
</style>
<body marginwidth="0" marginheight="0">
<div id="block_error">
    <div>
        <h2 style="color: red; font-weight: 600;">
            @if(Session::has('message'))
                {{ Session::get('message') }}
            @endif
        </h2>
        <p>
            It apperrs that Either something went wrong or the page doesn't exist anymore..<br />
            This website is temporarily unable to service your request as it has exceeded it’s resource limit. Please check back shortly.
        </p>
        <p>
            If you are the owner of the account and are regularly seeing this error, please read more about it in our <a href="http://www.namecheap.com/support/knowledgebase/article.aspx/1128/103/what-happens-when-my-account-reaches-lve-limits-diagnosing-and-resolving">knowledgebase</a>.
            If you have any questions, please contact our Technical Support department.
        </p>
    </div>
</div>
</body>

resources/views/admins/layouts/header.blade.php
<!-- Header-->
<header id="header" class="header">
    <div class="header-menu">
        <div class="col-sm-7">
            <a id="menuToggle" class="menutoggle pull-left"><i class="fa fa fa-tasks"></i></a>
            <div class="header-left">
                <button class="search-trigger"><i class="fa fa-search"></i></button>
                <div class="form-inline">
                    <form class="search-form">
                        <input class="form-control mr-sm-2" type="text" placeholder="Search ..." aria-label="Search">
                        <button class="search-close" type="submit"><i class="fa fa-close"></i></button>
                    </form>
                </div>

                <div class="dropdown for-notification">
                    <button class="btn btn-secondary dropdown-toggle" type="button" id="notification" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fa fa-bell"></i>
                        <span class="count bg-danger">5</span>
                    </button>
                    <div class="dropdown-menu" aria-labelledby="notification">
                        <p class="red">You have 3 Notification</p>
                        <a class="dropdown-item media bg-flat-color-1" href="#">
                            <i class="fa fa-check"></i>
                            <p>Server #1 overloaded.</p>
                        </a>
                        <a class="dropdown-item media bg-flat-color-4" href="#">
                            <i class="fa fa-info"></i>
                            <p>Server #2 overloaded.</p>
                        </a>
                        <a class="dropdown-item media bg-flat-color-5" href="#">
                            <i class="fa fa-warning"></i>
                            <p>Server #3 overloaded.</p>
                        </a>
                    </div>
                </div>

                <div class="dropdown for-message">
                    <button class="btn btn-secondary dropdown-toggle" type="button"
                            id="message"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="ti-email"></i>
                        <span class="count bg-primary">9</span>
                    </button>
                    <div class="dropdown-menu" aria-labelledby="message">
                        <p class="red">You have 4 Mails</p>
                        <a class="dropdown-item media bg-flat-color-1" href="#">
                            <span class="photo media-left"><img alt="avatar" src="admins/images/avatar/1.jpg"></span>
                            <span class="message media-body">
                                    <span class="name float-left">Jonathan Smith</span>
                                    <span class="time float-right">Just now</span>
                                        <p>Hello, this is an example msg</p>
                                </span>
                        </a>
                        <a class="dropdown-item media bg-flat-color-4" href="#">
                            <span class="photo media-left"><img alt="avatar" src="admins/images/avatar/2.jpg"></span>
                            <span class="message media-body">
                                    <span class="name float-left">Jack Sanders</span>
                                    <span class="time float-right">5 minutes ago</span>
                                        <p>Lorem ipsum dolor sit amet, consectetur</p>
                                </span>
                        </a>
                        <a class="dropdown-item media bg-flat-color-5" href="#">
                            <span class="photo media-left"><img alt="avatar" src="admins/images/avatar/3.jpg"></span>
                            <span class="message media-body">
                                    <span class="name float-left">Cheryl Wheeler</span>
                                    <span class="time float-right">10 minutes ago</span>
                                        <p>Hello, this is an example msg</p>
                                </span>
                        </a>
                        <a class="dropdown-item media bg-flat-color-3" href="#">
                            <span class="photo media-left"><img alt="avatar" src="admins/images/avatar/4.jpg"></span>
                            <span class="message media-body">
                                    <span class="name float-left">Rachel Santos</span>
                                    <span class="time float-right">15 minutes ago</span>
                                        <p>Lorem ipsum dolor sit amet, consectetur</p>
                                </span>
                        </a>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-sm-5">
            <div class="user-area dropdown float-right">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <img class="user-avatar rounded-circle" src="{{ auth()->user()->avatar ? asset('uploads/user/profile').'/'.auth()->user()->avatar : 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKhbXaYAEtIkRRBEREL0jwQUEERsDeHTjH_5vD7Ssm6JsfMLhg8Q&s' }}" alt="{{ auth()->user()->avatar }}">
                </a>

                <div class="user-menu dropdown-menu">
                    <a class="nav-link" href="{{ route('profile.edit', ['user' => auth()->user()->id]) }}"><i class="fa fa-user"></i> My Profile</a>

                    <a class="nav-link" href="#"><i class="fa fa-user"></i> Notifications <span class="count">13</span></a>

                    <a class="nav-link" id="changePassword" data-id="{{ auth()->user()->id }}" href="javascript:void(0)"><i class="fa fa-cog"></i> Change Pass</a>
                    <form action="{{ route('logout') }}" method="post">
                        @csrf
                        <button type="submit" style="background: transparent; border: none; padding: 0"><a class="nav-link"><i class="fa fa-power-off"></i> Logout</a></button>
                    </form>
                </div>
            </div>

            <div class="language-select dropdown" id="language-select">
                <a class="dropdown-toggle" href="#" data-toggle="dropdown"  id="language" aria-haspopup="true" aria-expanded="true">
                    <i class="flag-icon flag-icon-us"></i>
                </a>
                <div class="dropdown-menu" aria-labelledby="language">
                    <div class="dropdown-item">
                        <span class="flag-icon flag-icon-fr"></span>
                    </div>
                    <div class="dropdown-item">
                        <i class="flag-icon flag-icon-es"></i>
                    </div>
                    <div class="dropdown-item">
                        <i class="flag-icon flag-icon-us"></i>
                    </div>
                    <div class="dropdown-item">
                        <i class="flag-icon flag-icon-it"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {{-- modal change-password   --}}
    <div class="modal fade" id="changePwdModal" tabindex="-1" role="dialog" aria-labelledby="mediumModalLabel" style="display: none;" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="mediumModalLabel">Thay đổi mật khẩu</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form action="#" id="formChangePass" method="POST">
                        @csrf
                        <div class="form-group">
                            <label>Mật khẩu cũ</label>
                            <input type="password" name="password" id="password" class="form-control" placeholder="Password">
                        </div>
                        <div class="form-group">
                            <label>Mật khẩu mới</label>
                            <input type="password" name="passwordNew" id="passwordNew" class="form-control" placeholder="Password">
                        </div>
                        <div class="form-group">
                            <label>Nhập lại mật khẩu</label>
                            <input type="password" name="passwordConfirm" id="passwordConfirm" class="form-control" placeholder="Password Confirm">
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Hủy</button>
                            <button type="submit" class="btn btn-primary">Xác nhận</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</header><!-- /header -->
<!-- Header-->

resources/views/admins/layouts/master.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>Hệ thống quản lý bán hàng</title>
    <base href="{{ asset('/') }}">
    <link rel="apple-touch-icon" href="apple-icon.png">
    <link rel="shortcut icon" href="favicon.ico">
    <link rel="stylesheet" href="admins/vendors/bootstrap/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="admins/vendors/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="admins/vendors/themify-icons/css/themify-icons.css">
    <link rel="stylesheet" href="admins/vendors/flag-icon-css/css/flag-icon.min.css">
    <link rel="stylesheet" href="admins/vendors/selectFX/css/cs-skin-elastic.css">
    <style>
        .error {
            color: #d20707;
            font-size: 15px;
            font-weight: 400;
            margin-top: 5px;
            letter-spacing: 1px;
        }
    </style>
    @yield('styles')
    <link rel="stylesheet" href="admins/assets/css/style.css">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700,800' rel='stylesheet' type='text/css'>
</head>
<body>
<aside id="left-panel" class="left-panel">
    @include('admins.layouts.sidebar')
</aside>
<div id="right-panel" class="right-panel">
    @include('admins.layouts.header')
    @include('admins.layouts.breadcrumb')
    @yield('main')
</div>
<script src="admins/vendors/plugins/sweetalert2@9.js"></script>
<script src="admins/vendors/plugins/jquery.min.js"></script>
<script src="admins/vendors/tinymce/tinymce.min.js"></script>
<script src="admins/vendors/plugins/jquery.validate.min.js"></script>
<script src="admins/builds/base/baseajax.js"></script>
<script src="admins/builds/modules/auth/changepwdajax.js"></script>
@yield('ajax')
<script src="admins/vendors/popper.js/dist/umd/popper.min.js"></script>
<script src="admins/vendors/bootstrap/dist/js/bootstrap.min.js"></script>
<script src="admins/assets/js/main.js"></script>
<script src="admins/builds/base/basecustom.js"></script>
@yield('scripts')
</body>
</html>

resources/views/admins/layouts/sidebar.blade.php
<nav class="navbar navbar-expand-sm navbar-default">

    <div class="navbar-header">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#main-menu" aria-controls="main-menu" aria-expanded="false" aria-label="Toggle navigation">
            <i class="fa fa-bars"></i>
        </button>
        <a class="navbar-brand" href="./"><img src="admins/images/logo.png" alt="Logo"></a>
        <a class="navbar-brand hidden" href="./"><img src="admins/images/logo2.png" alt="Logo"></a>
    </div>

    <div id="main-menu" class="main-menu collapse navbar-collapse">
        <ul class="nav navbar-nav">
            <li class="active">
                <a href=""> <i class="menu-icon fa fa-dashboard"></i>Dashboard </a>
            </li>
            <h3 class="menu-title">Hệ thống</h3><!-- /.menu-title -->
            <li class="active">
                <a href=""> <i class="menu-icon fa fa-users"></i>Kho hàng </a>
            </li>
            <li class="menu-item-has-children dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-laptop"></i>Thành viên</a>
                <ul class="sub-menu children dropdown-menu">
                    <li><i class="fa fa-puzzle-piece"></i><a href="{{ route('roles.index') }}">Nhóm quyền</a></li>
                    <li><i class="fa fa-id-badge"></i><a href="{{ route('users.index') }}">Quản lý thành viên</a></li>
                </ul>
            </li>
            <li class="menu-item-has-children dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-table"></i>Sản phẩm</a>
                <ul class="sub-menu children dropdown-menu">
                    <li><i class="fa fa-table"></i><a href="{{ route('categories.index') }}">Danh mục</a></li>
                    <li><i class="fa fa-table"></i><a href="{{ route('brands.index') }}">Thương hiệu</a></li>
                    <li><i class="fa fa-table"></i><a href="{{ route('products.index') }}">Sản phẩm</a></li>
                </ul>
            </li>
            <li class="menu-item-has-children dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-th"></i>Nhà cung cấp</a>
                <ul class="sub-menu children dropdown-menu">
                    <li><i class="menu-icon fa fa-th"></i><a href="">Danh sách</a></li>
                    <li><i class="menu-icon fa fa-th"></i><a href="">Sản phẩm cung cấp</a></li>
                </ul>
            </li>
            <li class="active">
                <a href=""> <i class="menu-icon fa fa-users"></i>Cài đặt web </a>
            </li>
        </ul>
    </div><!-- /.navbar-collapse -->
</nav>

resources/views/admins/layouts/template-mail.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Forget Password Template</title>
    <style>
        .logo_text {
            font-family: 'Roboto Slab', serif;
            font-size: 50px;
            font-weight: 700;
            line-height: 0.75;
            /* color: #384158; */
            color: #6d1369;
            vertical-align: middle;
            margin-left: 7px;
            -webkit-transition: all 200ms ease;
            -moz-transition: all 200ms ease;
            -ms-transition: all 200ms ease;
            -o-transition: all 200ms ease;
            transition: all 200ms ease;
            text-transform: uppercase;
        }
        .logo_text span {
            color: #f26b23;
        }
        .template-mail__inner {
            padding: 30px 0;
        }
        .template-mail__content {
            padding: 0 15px;
        }
    </style>
</head>
<body>
<div class="template-mail">
    <div class="template-mail__inner">
        <div class="template-mail__head logo_text">
            Ecommerce <span>System</span>
        </div>
        <div class="template-mail__content">
            <h3>Mã code reset Password:</h3>
            <h1 style="font-weight: bold; color: black; font-size: 60px">{!! $e_message !!}</h1>
        </div>
    </div>
</div>
</body>
</html>